## 张量
### 1.概念
        (1)标量（0阶张量）: 只有大小，没有方向。
        (2)向量（1阶张量）: 
                (2.1)笛卡尔坐标系的概念: 基向量（大小为1，方向为坐标轴方向）
                (2.2)明确基向量表示向量的方法

        m维张量可以看作m-1维张量在某个方向上的堆叠
### 2.基本处理
        (1)flatten:张量(c,w,h),start_dim = 0, end_dim = 1 ---> (cw,h)   (3,5,6,7) ---> (15,6,7)

        Pytorch中常见的张量生成方法如下，大部分操作与Numpy中的操作指令类似，如果构建时不声明张量的数据类型。一般会默认为float32

In [2]:
import torch
#构造一个默认Float型的张量
tensor_1 = torch.tensor((3,3))
print(tensor_1)

#构造一个无初始化定义的张量
tensor_2 = torch.empty((3,3))
print(tensor_2)

#构造一个随机初始化的矩阵（值在0到1之间）
tensor_3 = torch.rand((3,3))
print(tensor_3)

#构造一个0元素矩阵
tensor_4 = torch.zeros((3,3))
print(tensor_4)

#构造一个元素全为1的矩阵
tensor_5 = torch.ones((3,3))
print(tensor_5)

tensor([3, 3])
tensor([[-2.2414e-36,  4.5846e-41, -9.0693e+11],
        [ 3.0618e-41,  9.7643e+26,  4.5846e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[0.9518, 0.7579, 0.4954],
        [0.2569, 0.8091, 0.2045],
        [0.7025, 0.2021, 0.4296]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


        Pytorch中提供的与Numpy数据之间的相互转换，转换过程不影响我们的数据类型，数据类型必须保持一致

In [9]:
import numpy as np
#tensor转numpy
t1 = torch.randn((3,3))
#构建3X3元素的随机的tensor
t1_numpy = t1.numpy()
print(t1, "\n", t1_numpy)
#numpy转换为tensor
#构建numpy格式的矩阵
t1_numpy = np.array([[2,3],[4,5],[6,7]])
t1_torch = torch.from_numpy(t1_numpy)
print(t1_numpy, "\n", t1_torch)

tensor([[ 0.9406, -1.1957,  1.0582],
        [-1.1807,  0.0202, -0.0681],
        [-0.1489, -1.3617,  0.0595]]) 
 [[ 0.9405561  -1.1956948   1.0581717 ]
 [-1.1807301   0.02020014 -0.0681175 ]
 [-0.14894292 -1.3616508   0.05954116]]
[[2 3]
 [4 5]
 [6 7]] 
 tensor([[2, 3],
        [4, 5],
        [6, 7]])


        Pytorch中的张量基本操作
        形状查看及更改：在张量做加减乘除等运算时，需要保证张量的形状一致，往往需要对某些张量进行更改

In [37]:
import torch
import numpy as np
t1 = torch.randn((3,3)) # 构建 3 × 3 元素随机的 tensor
shape = t1.shape # 返回张量的维度 torchsize([3,3]), 也可以通过 tl size() 查看
print(shape)

torch.Size([3, 3])


In [44]:
print(t1)
t1_reshape = t1.reshape(1,9)
print(t1_reshape)

tensor([[-0.9577, -0.5508,  0.0897],
        [-1.4344, -1.6909, -0.3070],
        [ 0.0591, -1.0154, -1.0140]])
tensor([[-0.9577, -0.5508,  0.0897, -1.4344, -1.6909, -0.3070,  0.0591, -1.0154,
         -1.0140]])


In [39]:
print(t1)
t1_resize = t1.resize(1,9) # 重构成 torch.size([1,9]),resize有两种使用方式，一种是没有返回值的，直接对原始的数据进行修改，还有一种用法是有返回值的，所以不会修改原有的数组值。,reshape不会修改原始数据的数据，而是返回一个新的数组
print(t1_resize)

tensor([[-0.9577, -0.5508,  0.0897],
        [-1.4344, -1.6909, -0.3070],
        [ 0.0591, -1.0154, -1.0140]])
tensor([[-0.9577, -0.5508,  0.0897, -1.4344, -1.6909, -0.3070,  0.0591, -1.0154,
         -1.0140]])


In [47]:
import numpy as np
X=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
 
X_new=np.resize(X,(3,3)) # do not change the original X
print("X:\n",X)  #original X
print("X_new:\n",X_new) # new X

X:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
X_new:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
import numpy as np
X=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

X_2=X.resize((3,3))  #change the original X ,and do not return a value
print("X:\n",X)  # change the original X
print("X_2:\n",X_2) # return None

X:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
X_2:
 None


In [16]:
t1 = torch.randn((3,3))
print(t1)
t1_view = t1.view(-1)# 拉伸成一维张量 torchsize([9J
print(t1_view)

tensor([[-0.9609, -0.4447,  0.7242],
        [-0.3501, -1.1566, -0.7684],
        [-0.9761, -0.7472,  0.1473]])
tensor([-0.9609, -0.4447,  0.7242, -0.3501, -1.1566, -0.7684, -0.9761, -0.7472,
         0.1473])


In [22]:
t1 = torch.randn((3,3))
print(t1)
t1_unsqueeze = torch.unsqueeze(t1,dim=0) # 增添维度 ， 结果为 torch.size([1,3,3])
print(t1_unsqueeze)


tensor([[-0.0801, -0.0322,  1.2713],
        [ 0.0085, -0.7158,  0.3796],
        [-0.7162,  0.1358,  0.1996]])
tensor([[[-0.0801, -0.0322,  1.2713],
         [ 0.0085, -0.7158,  0.3796],
         [-0.7162,  0.1358,  0.1996]]])


In [23]:
t1_squeeze = torch.squeeze(t1_unsqueeze,dim=0) # 删减维度结果为 torch.size([3])
print(t1_squeeze)

tensor([[-0.0801, -0.0322,  1.2713],
        [ 0.0085, -0.7158,  0.3796],
        [-0.7162,  0.1358,  0.1996]])


        Flatten:张量(c,w,h),start_dim = 0, end_dim = 1 ---> (cw,h)   (3,5,6,7) ---> (15,6,7)

In [21]:
t1 = torch.randn((3,3))
print(t1)
t1_flatten = torch.flatten(t1) # 将两个维度间的元素进行拉伸 ， 结果为 torchsize([9])
print(t1_flatten)

tensor([[ 0.7985, -1.3607, -0.0365],
        [-0.7026, -1.5255,  0.8040],
        [ 0.5479,  0.3249, -0.1690]])
tensor([ 0.7985, -1.3607, -0.0365, -0.7026, -1.5255,  0.8040,  0.5479,  0.3249,
        -0.1690])


In [55]:
import torch
import numpy as np
tensor_1 = torch.randn((2,3,4))
print(tensor_1)
print(tensor_1.shape)
tensor_2 = torch.flatten(tensor_1,start_dim=1)
print(tensor_2)
print(tensor_2.shape)
tensor_3 = torch.flatten(tensor_1,start_dim=0,end_dim=1)
print(tensor_3)
print(tensor_3.shape)
tensor_4 = torch.flatten(tensor_1,start_dim=0,end_dim=2)
print(tensor_4)
print(tensor_4.shape)

tensor([[[-0.2457, -0.7202,  0.5922,  1.4378],
         [ 0.4030, -1.2694, -0.7379, -0.6510],
         [-0.6833,  0.8025, -0.3791, -1.2830]],

        [[ 0.5835,  0.4434, -0.1102,  0.5180],
         [ 1.5095,  0.0809, -1.4482, -1.4230],
         [-0.2016, -0.2890,  0.2557, -1.5615]]])
torch.Size([2, 3, 4])
tensor([[-0.2457, -0.7202,  0.5922,  1.4378,  0.4030, -1.2694, -0.7379, -0.6510,
         -0.6833,  0.8025, -0.3791, -1.2830],
        [ 0.5835,  0.4434, -0.1102,  0.5180,  1.5095,  0.0809, -1.4482, -1.4230,
         -0.2016, -0.2890,  0.2557, -1.5615]])
torch.Size([2, 12])
tensor([[-0.2457, -0.7202,  0.5922,  1.4378],
        [ 0.4030, -1.2694, -0.7379, -0.6510],
        [-0.6833,  0.8025, -0.3791, -1.2830],
        [ 0.5835,  0.4434, -0.1102,  0.5180],
        [ 1.5095,  0.0809, -1.4482, -1.4230],
        [-0.2016, -0.2890,  0.2557, -1.5615]])
torch.Size([6, 4])
tensor([-0.2457, -0.7202,  0.5922,  1.4378,  0.4030, -1.2694, -0.7379, -0.6510,
        -0.6833,  0.8025, -0.3791, -1.283

        拼接与拆分: 在神经网络的前向传播过程中, 往往需要对多个分支的张量加以融合或拆分。
        cat在CV常用，而stack在NLP常用，chunk相当于将块进行分离拼接

In [65]:
import torch
tensor1 = torch.randn((1,2,2,2))
tensor2 = torch.randn((1,2,2,2))
tensor3 = torch.cat((tensor1,tensor2),dim=0)
#t1=[], t2=[], t3=[[],[]] 
print(tensor1)
print(tensor2)
print(tensor3)
print(tensor3.shape)

tensor([[[[ 0.3708,  1.3519],
          [ 1.6196,  2.5773]],

         [[ 1.7270, -0.3816],
          [ 0.5572,  0.5273]]]])
tensor([[[[ 0.4607,  1.4197],
          [ 0.7299,  0.4440]],

         [[-0.5487,  0.5166],
          [ 0.3944,  0.1565]]]])
tensor([[[[ 0.3708,  1.3519],
          [ 1.6196,  2.5773]],

         [[ 1.7270, -0.3816],
          [ 0.5572,  0.5273]]],


        [[[ 0.4607,  1.4197],
          [ 0.7299,  0.4440]],

         [[-0.5487,  0.5166],
          [ 0.3944,  0.1565]]]])
torch.Size([2, 2, 2, 2])


        PyTorch 中封装了很多关于张量的基本计算方法

In [74]:
import torch
a = torch.ones(1,2)
b = torch.ones(1,2)
c = torch.randn(2,2)
add = a + b # 加法运算
sub = a - b # 减法运算
div = a/b # 除法运算
mul = a*b # 乘法运算 ， 也可以用@或 matmul
max = c.max() # 求解最大元素
am = c.argmax()
min = c.min() # 求解最小元素
amin = c.argmin()
print(a,"\n",b,"\n",c)
print(add)
print(sub)
print(div)
print(mul)
print(max,am)
print(min,amin)


tensor([[1., 1.]]) 
 tensor([[1., 1.]]) 
 tensor([[ 1.7001,  0.4188],
        [-0.3061, -0.2500]])
tensor([[2., 2.]])
tensor([[0., 0.]])
tensor([[1., 1.]])
tensor([[1., 1.]])
tensor(1.7001) tensor(0)
tensor(-0.3061) tensor(2)


        自动求导
![求导](Pic/image1.png)

In [83]:
import torch
x = torch.Tensor([2])#定义输入张量
# 初始化权重参数w，偏移量 b，并设置 require-grad为 True，为自动求导
w = torch.randn(1,requires_grad=True)
b = torch.randn(1,requires_grad=True)
y = torch.mul(w,x)
z = torch.add(y,b)#等价于y+b
z.backward()#标量进行反向传播。向量需要构建梯度矩阵
print(x,"\n",w,"\n",b,"\n",y)
print(z)


tensor([2.]) 
 tensor([2.1259], requires_grad=True) 
 tensor([0.8356], requires_grad=True) 
 tensor([4.2519], grad_fn=<MulBackward0>)
tensor([5.0874], grad_fn=<AddBackward0>)
None


/tmp/ipykernel_6611/1797186573.py:11: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print(y.grad)


![求导](Pic/image2.png)