## 张量
### 1.概念
        (1)标量（0阶张量）：只有大小，没有方向。
        (2)向量（1阶张量）：笛卡尔坐标系的概念：基向量（大小为1，方向为坐标轴方向）
        m维张量可以看作m-1维张量在某个方向上的堆叠

        Pytorch中常见的张量生成方法如下，大部分操作与Numpy中的操作指令类似，如果构建时不声明张量的数据类型。一般会默认为float32

In [8]:
import torch
#构造一个默认Float型的张量
tensor_1 = torch.tensor((3,3))
print(tensor_1)

#构造一个无初始化定义的张量
tensor_2 = torch.empty((3,3))
print(tensor_2)

#构造一个随机初始化的矩阵
tensor_3 = torch.rand((3,3))
print(tensor_3)

#构造一个0元素矩阵
tensor_4 = torch.zeros((3,3))
print(tensor_4)

#构造一个元素全为1的矩阵
tensor_5 = torch.ones((3,3))
print(tensor_5)

1.7.1+cu110
11.0
tensor([3, 3])
tensor([[-5.6912e+29,  4.5671e-41, -1.1711e+18],
        [ 3.0938e-41,  4.4842e-44,  0.0000e+00],
        [ 1.5695e-43,  0.0000e+00, -1.1711e+18]])
tensor([[0.8843, 0.2751, 0.2441],
        [0.4253, 0.4042, 0.0788],
        [0.1628, 0.9006, 0.6550]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


        Pytorch中提供的与Numpy数据之间的相互转换，转换过程不影响我们的数据类型，数据类型必须保持一致

In [9]:
import numpy as np
#tensor转numpy
t1 = torch.randn((3,3))
#构建3X3元素的随机的tensor
t1_numpy = t1.numpy()
print(t1, "\n", t1_numpy)
#numpy转换为tensor
#构建numpy格式的矩阵
t1_numpy = np.array([[2,3],[4,5],[6,7]])
t1_torch = torch.from_numpy(t1_numpy)
print(t1_numpy, "\n", t1_torch)

tensor([[ 0.9406, -1.1957,  1.0582],
        [-1.1807,  0.0202, -0.0681],
        [-0.1489, -1.3617,  0.0595]]) 
 [[ 0.9405561  -1.1956948   1.0581717 ]
 [-1.1807301   0.02020014 -0.0681175 ]
 [-0.14894292 -1.3616508   0.05954116]]
[[2 3]
 [4 5]
 [6 7]] 
 tensor([[2, 3],
        [4, 5],
        [6, 7]])


        Pytorch中的张量基本操作
        形状查看及更改：在张量做加减乘除等运算时，需要保证张量的形状一致，往往需要对某些张量进行更改

In [10]:
import torch
import numpy as np
t1 = torch.randn((3,3)) # 构建 3 × 3 元素随机的 tensor
shape = t1.shape # 返回张量的维度 torchsize([3,3]), 也可以通过 tl size() 查看
print(shape)

torch.Size([3, 3])


In [11]:
print(t1)
t1_resize = t1.resize_(1,9) # 重构成 torch.size([1,9])
print(t1_resize)

tensor([[ 0.2480, -0.6336,  0.8917],
        [-0.2698,  0.9942,  0.3458],
        [ 1.1079, -0.0400, -0.4591]])
tensor([[ 0.2480, -0.6336,  0.8917, -0.2698,  0.9942,  0.3458,  1.1079, -0.0400,
         -0.4591]])


In [12]:
print(t1)
t1_view = t1.view(-1)# 拉伸成一维张量 torchsize([9J
print(t1_view)

tensor([[ 0.2480, -0.6336,  0.8917, -0.2698,  0.9942,  0.3458,  1.1079, -0.0400,
         -0.4591]])
tensor([ 0.2480, -0.6336,  0.8917, -0.2698,  0.9942,  0.3458,  1.1079, -0.0400,
        -0.4591])


In [ ]:
t1.unsqueeze = torch.unsqueeze(t1,dim=0) # 增添维度 ， 结果为 torch.size([1,3,3])
t1.squeeze = torch.squeeze(t1,dim=0) # 删减维度结果为 torch.size([3])
t1.flatten = torch.flatten(t1) # 将两个维度间的元素进行拉伸 ， 结果为 torchsize([9])